version: '3.8'

services:

  web:
    image: nginx:latest
    container_name: web
    restart: always
    depends_on:
      - frontend
    ports:
      - 80:80
    volumes:
      - ./cable_nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app
  #      - ./cable_fe:/usr/share/nginx/html

  api:
    image: cable_be:latest
    container_name: api
    restart: always
    ports:
      - 8080:8080
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: cable_db
    depends_on:
      - db
    networks:
      - app

  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: cable_db
    networks:
      - app

  frontend:
    image: cable_fe:latest
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
#    links:
#      - api
    networks:
      - app

networks:
  app: